// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_image_src(ui_Screen1, &ui_img_no8hx_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pressure = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_pressure);
    lv_obj_set_width(ui_pressure, 45);
    lv_obj_set_height(ui_pressure, 16);
    lv_obj_set_x(ui_pressure, 44);
    lv_obj_set_y(ui_pressure, 37);
    lv_obj_set_align(ui_pressure, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_pressure, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_temperature = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_temperature);
    lv_obj_set_width(ui_temperature, 45);
    lv_obj_set_height(ui_temperature, 16);
    lv_obj_set_x(ui_temperature, 43);
    lv_obj_set_y(ui_temperature, -18);
    lv_obj_set_align(ui_temperature, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_temperature, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_humidity = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_humidity);
    lv_obj_set_width(ui_humidity, 45);
    lv_obj_set_height(ui_humidity, 16);
    lv_obj_set_x(ui_humidity, 41);
    lv_obj_set_y(ui_humidity, 2);
    lv_obj_set_align(ui_humidity, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_humidity, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_Label1 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_Label1, -1);
    lv_obj_set_y(ui_Label1, -51);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "ESP32 Weather Station");
    lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_Label2, -35);
    lv_obj_set_y(ui_Label2, -20);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "Temperature °C");
    lv_obj_set_style_text_color(ui_Label2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label2, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_Label3, -45);
    lv_obj_set_y(ui_Label3, 1);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "Humidity %");
    lv_obj_set_style_text_color(ui_Label3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label3, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label4 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_Label4, -35);
    lv_obj_set_y(ui_Label4, 36);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "Air pressure hPa");
    lv_obj_set_style_text_color(ui_Label4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label4, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_bar = lv_bar_create(ui_Screen1);
    lv_bar_set_value(ui_bar, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_bar, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_bar, 126);
    lv_obj_set_height(ui_bar, 8);
    lv_obj_set_x(ui_bar, -2);
    lv_obj_set_y(ui_bar, 19);
    lv_obj_set_align(ui_bar, LV_ALIGN_CENTER);

    // Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if (lv_obj_get_style_pad_top(ui_bar, LV_PART_MAIN) > 0)
        lv_obj_set_style_pad_right(ui_bar,
                                   lv_obj_get_style_pad_right(ui_bar, LV_PART_MAIN) + 1, LV_PART_MAIN);
}
